### ISSUE TITLE
Paraview error with 2D adapted grid result files

### ISSUE THREAD

**Issue by aklothakis** [sparta/sparta#328]
## Summary

Paraview error with 2D adapted grid result files

## Type of Issue

Bug report

## Detailed Description (Bug report)

When converting a 2D result file to .pvd with grid2paraview.py it produces an error in Paraview. The error message is "Cannot read cell data array. The data array in the element may be too short".  I am using Paraview version 5.10.0 but the same error happens also in 5.8.1

## SPARTA Version (Bug Report)

07Jan22

## Expected Behavior (Bug Report)

The .pvd file should show the results fine in Paraview.

## Actual Behavior (Bug Report)

Cannot read file

**Comment by aklothakis** [comment]
Please find a zip with the required files to reproduce the issue in the link below.

[https://we.tl/t-g2ns6MtUC1](url)

**Comment by stanmoore1** [comment]
@aklothakis can you please repost the reproducer--it didn't come through in that link above--thanks. @tjotaha any ideas?

**Comment by aklothakis** [comment]
> @aklothakis can you please repost the reproducer--it didn't come through in that link above--thanks. @tjotaha any ideas?

@stanmoore1 Yes sure looks like Github is blocking the link. I am including one more result file in this one. If you run grid2paraview.py with the tmp_biconic.880000 as a results input then if you try to load it in Paraview you get an error message for the variables id,xlo,xhi. If you uncheck these then the .pvd opens and loads the result.

I included also 2 grid files one produced by the fix_adapt command (grid.120000) and an another one produced by the write_grid command. I am not sure why but looks like they differ in the number of lines. In both files the number of cells and the levels are the same though. Shouldn't both files have the same number of lines since the grid is the same?

This is a new link. Try and copy/paste it in a new browser tab manually and the zip will download.

https://we.tl/t-efpX5KmcF7

**Comment by stanmoore1** [comment]
I tried attaching the file here, but Github has a 25 MB size limit. I will send a copy to @tjotaha who is our Paraview expert.

**Comment by tjotaha** [comment]
@stanmoore1 Thanks for sending the data to reproduce this issue.

I ran grid2paraview.py with Grid.txt and no input flow files. I got out a Grid.pvd and a Grid directory with one pvtu file but no vtu files. This does not load correctly in ParaView, since the vtu files referred to by the pvtu file do not exist. 

I then modified grid2paraview.py slightly to force it to run single threaded and give more error output (this should be a command line option, so I'll open an issue to add this feature). This run produced the output shown below.

Upon inspection of the grid.120000 file, I noticed that there are some extraneous characters after the cell ids starting at line 111324 of the file. This is causing grid2paraview.py to fail while reading the cell ids to create the grid.

I was able to manually delete the line from the grid.120000 file and re-add it. This caused grid2paraview.py to succeed and produced a readable Grid.pvd file loadable by ParaView.

I then tried running with the flow files, but got a similar error. My impression is that there is Windows/Linux problem with text files. Was the data for this case created on a Windows machine?

```
[tjotaha@s1017867 ParaviewError]$ /data/tjotaha/src/ParaView-5.10.0-MPI-Linux-Python3.9-x86_64/bin/pvpython ../grid2paraview.py Grid.txt Grid
Processing  12  grid chunk(s).
Traceback (most recent call last):
  File "/data/tjotaha/src/sparta_work/test_suite/sparta/tools/paraview/ParaviewError/../grid2paraview.py", line 1568, in <module>
    create_and_write_grid_chunk(idx, chunk, len(chunking), grid_desc, time_steps_dict,
  File "/data/tjotaha/src/sparta_work/test_suite/sparta/tools/paraview/ParaviewError/../grid2paraview.py", line 322, in create_and_write_grid_chunk
    ug = process_grid_chunk(chunk_id, chunk_info, num_chunks, \
  File "/data/tjotaha/src/sparta_work/test_suite/sparta/tools/paraview/ParaviewError/../grid2paraview.py", line 345, in process_grid_chunk
    read_grid_file(grid_desc, chunk_info)
  File "/data/tjotaha/src/sparta_work/test_suite/sparta/tools/paraview/ParaviewError/../grid2paraview.py", line 475, in read_grid_file
    for dashed_id in sgf:
  File "/data/tjotaha/src/sparta_work/test_suite/sparta/tools/paraview/ParaviewError/../grid2paraview.py", line 75, in next
    return self._get_next_cell()
  File "/data/tjotaha/src/sparta_work/test_suite/sparta/tools/paraview/ParaviewError/../grid2paraview.py", line 93, in _get_next_cell
    return self.create_dashed_id(local_cell_id)
  File "/data/tjotaha/src/sparta_work/test_suite/sparta/tools/paraview/ParaviewError/../grid2paraview.py", line 202, in create_dashed_id
    local_cell_id = int(local_cell_id)
ValueError: invalid literal for int() with base 10: '2899551\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
```

**Comment by stanmoore1** [comment]
Thanks @tjotaha!

**Comment by aklothakis** [comment]
Thanks @tjotaha for the info regarding this issue. The .vtu files were created in a linux cluster. Then I donwloaded the folder in my Windows box to plot it in Paraview. The files were made with pvpython 5.8.1 and I tried to view them with Paraview 5.10.0. I reran the simulation again to produce new files. The grid.120000 looks ok now I am attaching it below. Unfortunately, when I try to plot it in Paraview I get the following error:

"Cannot read cell data array f_3[2] from PointData in piece 0. The data array in the element may be too short."
[grid_120000.txt](https://github.com/sparta/sparta/files/8043180/grid_120000.txt)
[Grid.txt](https://github.com/sparta/sparta/files/8043181/Grid.txt)


This is the results file

[tmp_biconic.zip](https://github.com/sparta/sparta/files/8043259/tmp_biconic.zip)

**Comment by stanmoore1** [comment]
@aklothakis I can't reproduce this issue with latest `master` branch, is it still an issue for you?

**Comment by stanmoore1** [comment]
I had an AI look at this, and it added 3ddfdb9 which I think could help here, in PR #637.
